### ISSUE TITLE
PwmClock - reset issue

### ISSUE THREAD

**Issue by polyclash** [docb/dbRackSequencer#10]
is the `clocks[k].reset();` code missing here?
https://github.com/docb/dbRackSequencer/blob/3b940134abbc4227498ec385a48cf66dd87fe1cb/src/PwmClock.cpp#L188-L193

**Comment by docb** [comment]
well, i do not find any reason why its missing. so I'll fix it for the next version.

**Comment by polyclash** [comment]
Great, thank you.

**Comment by docb** [comment]
fixed in 2.1.0
