### ISSUE TITLE
Mini Matrix [new module]

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackSequencer#11]
The only reason I dare to ask is because I know that you also have a soft spot for compact sized modules. :) Would you please consider a mini version of theMatrix?

Probably you don't even need to change the code much you just skip a few addInput() and addParam() lines not is use. My proposal (see below) contains _no new_ parameters/socket at all.  

![image](https://user-images.githubusercontent.com/34127628/179514763-95f36486-2ac8-411c-882e-c3feeba561a9.png)

Best regards, Andras

**Comment by docb** [comment]
hi Andras,
i wonder what's the usecase.
Is it for having 4 tracks in y direction?
The Lvl parameter would be necessary,  btw.
best regards,
Christian

**Comment by firolightfog** [comment]
Hallo,

It's pure ergonomics. No new uses cases.

Currently I can set up a 32x32 matrix with diverse areas. Various ranges, various density. With a reading head for the rhythm, another one for the modulation, a third one for the notes of VCO, one more for the filter modulation, and so on ... 

But I found myself ignoring theMatrix because it's too big. Too much thing at one place. And noone wants to put a big mess into the center of his patch. In my experience I need a dedicated module to look at if I'm working with my rhythm section. Then another one once I'm wiggling with the drone layer. Etc.

Reducing the size to miniMatrix still offers an unmatched set of features. It is a 1-128 step CV sequencer with multiple reading heads. With the option of crazy playback routes and not to be repeated again. Anything like this in VCV!

As of LvL: it's good to have it on the panel but I don't think it's crucial. As I'm using the output of different reading heads for different purposes I'll by using dedicated VCAs for the outputs anyway.

Regards, Andras

**Comment by firolightfog** [comment]
Oh, I think I missed your real question... |:-}

Yes, even a single column of characters is enough. No need for 4 columns. I just automatically thought that 4 looks good.

**Comment by docb** [comment]
yes this was also in mind. but if there is only one column wouldn't then be then next question to use better symbols e.g. C0, C#0 ... - C6 or something similar?

**Comment by firolightfog** [comment]
No.

Having letters (ABcD...) allows a much more flexible application in the same place. Please note that C0 would require two columns, representing _note_ and _octave_ information. I'd preferably have those two columns separately for multiple purposes. 

So my vote is "no" for the C0, C#0 ... - C6 appearance. (But I have to admit that I'm very interested in [trackers](https://en.wikipedia.org/wiki/Scream_Tracker) for VCV. There's [a single tracker](https://library.vcvrack.com/regen-modular/regen-frames) in the Library at the moment as well as I know. It is commercial unfortunately but a very nice one!)

**Comment by docb** [comment]
aa371d9d6d1308716d4e43b348eb6e7b6e6c526c
on the development branch  there is now a mini matrix with exact identical function.
![image](https://user-images.githubusercontent.com/1134412/230653908-0eb45bf7-e61f-4f81-9f8d-ddf430f3996b.png)

**Comment by firolightfog** [comment]
I can't build a Win binary for testing at the moment.
So I wait a bit longer to put my hands on it. :)

**Comment by docb** [comment]
you can take this one: https://github.com/docb/dbRackSequencer/releases/tag/v2.3.0-dev01
