### ISSUE TITLE
M851 - step value saving issue when range -3/3V

### ISSUE THREAD

**Issue by Loop-s** [docb/dbRackSequencer#13]
Hi! With your M851 module, after right-clicking and choosing the -3/3V range, if you insert a step value lower than -2 or higher than 2, the value entered will remain correct while the patch is open in Rack. However, when closing and reopening the patch, any step value lower than -2 or higher than 2 will be rounded to fit within the -2/2V range again. For example, entered -2.5 as step value will change to -2 when reloading the patch.

![image](https://user-images.githubusercontent.com/110244461/184466299-73e3aa1d-6ab5-4a58-bd50-bb1b7bef68d5.png)

Never reported an issue before on github so let me know if you need anything else to help out.

Cheers,
Loops

**Comment by docb** [comment]
hi, thanks for reporting. however this issue should be solved in this pre release:
https://github.com/docb/dbRackSequencer/releases/tag/v2.1.0-pre1
would be great if you if you could verify
thanks

**Comment by Loop-s** [comment]
Indeed, just checked and it is fixed in v2.1.0. Tks!
