### ISSUE TITLE
Dragging cable over buttons will alter selection

### ISSUE THREAD

**Issue by Loop-s** [docb/dbRackSequencer#14]
Hi again! I'll use the M851 for my example but this seems to be happening to other modules with buttons like these : 

![image](https://user-images.githubusercontent.com/110244461/184466603-ad76b233-bc84-4f35-ac4b-6b8f753bf430.png)

When holding and dragging a cable in Rack, if you pass it over one of these button types, there's a chance it'll alter your button selections when hovering the cable over them.

In the example below, I'm starting to drag the cable from the RndC Tri output to one of the M851 CV step inputs : 

![image](https://user-images.githubusercontent.com/110244461/184466720-b0e73169-afca-4994-aeb7-c12a34895ba7.png)

After dropping the cable in one of those inputs, you can see that it changed two selections along the way : 

![image](https://user-images.githubusercontent.com/110244461/184466889-4e7d1b14-ab86-4e1a-838d-d66d3a0f2e15.png)

Let me know if you need any additional info.

Cheers,
Loops

**Comment by docb** [comment]
hi, again thanks for reporting. 
this issue also should be resolved in https://github.com/docb/dbRackSequencer/releases/tag/v2.1.0-pre1
would be great if you if you could verify
thanks

**Comment by Loop-s** [comment]
Just verified this one as well against v2.1.0 and the issue is no longer there. Tks!
