### ISSUE TITLE
CDiv division input suggestion 

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackSequencer#15]
<img width="159" alt="image" src="https://user-images.githubusercontent.com/34127628/189063816-39347b2c-6409-490d-bdf2-f2bdb301cd26.png">

I would suggest that 0V input should set the division value to 1:1 (instead of 1:10). I believe the current method is a bug.

Best regards, Andras

**Comment by docb** [comment]
hi Andras,
yes this is a bug - it will be fixed in the next version.
thanks !

**Comment by docb** [comment]
fixed in 2.1.0
