### ISSUE TITLE
Preset module crashes rack when paired with Vult Opulus

### ISSUE THREAD

**Issue by ContemporaryInsanity** [docb/dbRackSequencer#19]
[120.610 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
27: ./Rack() [0x403c8d]
26: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
25: /home/ewen/.Rack2/plugins/dbRackSequencer/plugin.so(Preset::updatePresets()+0xcd)
24: /home/ewen/.Rack2/plugins/dbRackSequencer/plugin.so(Presets::draw(rack::widget::Widget::DrawArgs const&)+0x115)
23: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
22: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
21: ./libRack.so(rack::app::ModuleWidget::draw(rack::widget::Widget::DrawArgs const&)+0x55)
20: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
19: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
18: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
17: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
16: ./libRack.so(rack::app::RackWidget::draw(rack::widget::Widget::DrawArgs const&)+0x32)
15: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
14: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
13: ./libRack.so(rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&)+0x4c)
12: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
11: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
10: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
9: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
8: ./libRack.so(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+0x34)
7: ./libRack.so(rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int)+0x124)
6: ./libRack.so(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+0xcc)
5: ./libRack.so(rack::window::Window::step()+0x8e2)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xbe0)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403bb9]

**Comment by docb** [comment]
hi thanks for the report. 
i cannot reproduce on Linux, VCV RackPro 2.1.2, Vult Free.
There seems to be something wrong with preset directory paths or when parsing the directory structure, are there some more log entries before the crash?

**Comment by docb** [comment]
due to inactivity
