### ISSUE TITLE
ACC step bug

### ISSUE THREAD

**Issue by iliasboufidis** [docb/dbRackSequencer#20]
hello, sorry if this is smth i don't understand and not a bug,
when i set ACC step to 0.083 it [properly] ascends semitone-wise. when i patch 0.083 it auto-multiplies the input by 0.1 and rises by 0.0083.

be well, (i love this counter :D )

**Comment by docb** [comment]
yes this is the desired behavior. The step input offers a range from -10V to 10V and maps these values to -1,1. The idea is that this may be more convenient as not many modules have output ranges between -1 and 1. So if there comes from somewhere a semitone voltage it must be multiplied by 10 first.

**Comment by iliasboufidis** [comment]
thank you very much for the quick response! be well!
