### ISSUE TITLE
Langdon's Ant hangs Rack 2.3.0

### ISSUE THREAD

**Issue by fractalgee** [docb/dbRackSequencer#23]
Just adding Langdon's Ant into a patch and zooming the view a bit hangs Rack 2.3.0 on MacOS with the spinning cursor of death. Has to be force quit as Rack does no longer respond. Nothing to be seen in the log.

MacOS 13.4, Rack 2.3.0

Sadly can't give you more info, but it's reliably hanging Rack. If view is zoomed when Rack was force-quit, opening it again with same patch hangs it again.

**Comment by docb** [comment]
@fractalgee  A version which likely fixes this issue is here:
https://github.com/docb/dbRackSequencer/releases/tag/v2.3.0-dev03

**Comment by fractalgee** [comment]
indeed, all working fine now. Tested all inputs and outs ( a couple inputs miss tooltips but no biggie there) and no more hang.
