### ISSUE TITLE
SigMod mode input question

### ISSUE THREAD

**Issue by pizzathehut893** [docb/dbRackSequencer#25]
Hello,
I've been using your module SigMod for the past few days, and enjoying the results so far!
I wanted to sequence the mode that the module is in while performing, and thought I could do so with the "mode input" to the right of the mode selection buttons.  However the mode doesn't change no matter what cv I send to it.  

Just wanted to inquire whether that's what the input is for, or if something else is required. 

Thank you!

**Comment by docb** [comment]
Hi, thanks for reporting, unfortunately the function was forgotten so the mod input does nothing.
I will put it in the next version i.e. then 0-2.5V means Mod, 2.5-7.5V SR and 7.5 -10V SEQ.

**Comment by pizzathehut893** [comment]
Thank you!

**Comment by docb** [comment]
you can check it out here: https://github.com/docb/dbRackSequencer/releases/tag/v2.3.2-dev
