### ISSUE TITLE
Which oscillator do you use in your demo videos?

### ISSUE THREAD

**Issue by anyway** [docb/dbRackSequencer#4]
First of all, a thousand thanks for the great collection of modules! I am currently working intensively with it. Incredible what can be done with it and I'm just getting started. And yes... you really don't go out into nature anymore ;-))

No problem, but just one question: which oscillator do you use in your demo videos? It sounds great and I have no idea which one it could be. I really hope that this is a VCV module.

Thanks in advance for a quick answer!

**Comment by docb** [comment]
ha, this surprises me, as i did something unusual (for me) and usual for others: I tried to work in depth with the VCV VCO and VCF in the examples. Mainly i used the square wave output passed to VCF and played around with PWM, Filter Cutoff, Res and Drive.

**Comment by anyway** [comment]
Oh, that's funny... I wouldn't have thought that these are VCV standard modules. Somehow they seem to harmonize very well with the polyphony of your modules. Maybe I should look into it more intensively sometime too. With your tips I was able to restore the sound perfectly. Thanks a lot for your quick reply!
