### ISSUE TITLE
N3 probability knob proposal

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackSequencer#5]
I'd like propose replacement of the _TRIG outputs_ with a set of _probability knobs_. (I'd keep the POLY TRIG output though.)

<img width="250" alt="image" src="https://user-images.githubusercontent.com/34127628/172803658-b965dcad-6cbf-4206-9364-898802795e52.png">

Having GATE _and_ TRIG _and_ CLOCK outputs seems to be a bit luxurious. They're mostly similar but I find myself adding modules to mildly ruin the rhythms anyway.

**Comment by docb** [comment]
i think that would be too late, as i don't want to destroy existing patches. an additional poly input would be possible.

**Comment by firolightfog** [comment]
Makes sense! Thanks for considering anyway!
