### ISSUE TITLE
theMatrix Rnd behaviour [enhancement]

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackSequencer#7]
Dear Christian,

Would you please consider limiting the Rnd function to the selected area (if available)? 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/34127628/175295309-c4add098-2bb5-40e0-97e5-120c6f4b8749.png">

That would allow me to create sections with more/less density and not ruining some of the catchy tunes I already have. (OK, this is not so common I admit. ;) )

Best regards, A.

**Comment by docb** [comment]
i think it makes sense. i will check.

**Comment by docb** [comment]
works, great feature, thanks! because now you can select a vertical bar of length one or two and trigger rnd per run. so we have a similar thing as in hexseq  with the '*'.

**Comment by docb** [comment]
Here the example altogether with ACC threshold parameter where the length of the sequence is controlled, and random generation on a selection on every ACC trig.

https://vimeo.com/manage/videos/724035618

**Comment by firolightfog** [comment]
Any expected date for a VCV Library release?

**Comment by docb** [comment]
still need time and energy to write the manual for 12 new modules. so cannot say.

**Comment by docb** [comment]
@firolightfog there is now a pre release 2.1.0 available.

**Comment by firolightfog** [comment]
Changes in v2.1.0 pre-release seem to be fine. (And I love the new color schemes... :) )

**Comment by firolightfog** [comment]
Could you please save the position of the selected/marked area into the JSON? Currently closing/reopening a patch would enable the random function shuffle the whole box. Cheers, Andras

**Comment by docb** [comment]
sure, no problem

**Comment by docb** [comment]
fixed in 2.1.0
